/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tcs.regrato.gui;

import com.tcs.regrato.event.MenuHandler;
import com.tcs.regrato.event.WindowEventHandler;
import com.tcs.regrato.modal.GuiModal;
import com.tcs.regrato.resources.AppIcon;



/**
 * 
 * @author 1299792
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    private GuiModal guiModal;
    public MainWindow() {
        initComponents();
        guiModal = GuiModal.getGuiModal();
        setEvent();
        setProperty();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        traceNameLabel = new javax.swing.JLabel();
        tranceNameValuejLabel = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        jLabelProgress = new javax.swing.JLabel();
        jLabelShowOutput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneOutputLogs = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNewTrace = new javax.swing.JMenuItem();
        jMenuItemStopTrace = new javax.swing.JMenuItem();
        jMenuItemOpenRunLogs = new javax.swing.JMenuItem();
        jMenuItemExtractPath = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCommandEditor = new javax.swing.JMenuItem();
        jMenuItemExtractEditor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemMflags = new javax.swing.JMenuItem();
        jMenuItemOpenCardOpener = new javax.swing.JMenuItem();
        jMenuItemDro = new javax.swing.JMenuItem();
        jMenuItemOption = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        traceNameLabel.setText("Trace Name :");

        tranceNameValuejLabel.setText(" ");

        jLabelProgress.setText("Progress");

        jLabelShowOutput.setText(" ");

        jScrollPane1.setViewportView(jTextPaneOutputLogs);

        jMenuFile.setText("File");

        jMenuItemNewTrace.setText("New Trace");
        jMenuFile.add(jMenuItemNewTrace);

        jMenuItemStopTrace.setText("Stop Trace");
        jMenuFile.add(jMenuItemStopTrace);

        jMenuItemOpenRunLogs.setText("Open Run Logs");
        jMenuFile.add(jMenuItemOpenRunLogs);

        jMenuItemExtractPath.setText("Open Extract Path");
        jMenuFile.add(jMenuItemExtractPath);

        jMenuBar1.add(jMenuFile);

        jMenu1.setText("Edit");

        jMenuItemCommandEditor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCommandEditor.setText("Command Editor");
        jMenu1.add(jMenuItemCommandEditor);

        jMenuItemExtractEditor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExtractEditor.setText("Extract Editor");
        jMenu1.add(jMenuItemExtractEditor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        jMenu3.setText("Region");

        jMenuItemMflags.setText("Date");
        jMenu3.add(jMenuItemMflags);

        jMenuItemOpenCardOpener.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemOpenCardOpener.setText("Card File");
        jMenu3.add(jMenuItemOpenCardOpener);

        jMenuItemDro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDro.setText("DRO/DRB");
        jMenu3.add(jMenuItemDro);

        jMenu2.add(jMenu3);

        jMenuItemOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOption.setText("Option");
        jMenuItemOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOptionActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemOption);

        jMenuBar1.add(jMenu2);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(traceNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tranceNameValuejLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelShowOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(traceNameLabel)
                    .addComponent(tranceNameValuejLabel))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProgress))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelShowOutput)
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOptionActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProgress;
    private javax.swing.JLabel jLabelShowOutput;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemCommandEditor;
    private javax.swing.JMenuItem jMenuItemDro;
    private javax.swing.JMenuItem jMenuItemExtractEditor;
    private javax.swing.JMenuItem jMenuItemExtractPath;
    private javax.swing.JMenuItem jMenuItemMflags;
    private javax.swing.JMenuItem jMenuItemNewTrace;
    private javax.swing.JMenuItem jMenuItemOpenCardOpener;
    private javax.swing.JMenuItem jMenuItemOpenRunLogs;
    private javax.swing.JMenuItem jMenuItemOption;
    private javax.swing.JMenuItem jMenuItemStopTrace;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneOutputLogs;
    private javax.swing.JLabel traceNameLabel;
    private javax.swing.JLabel tranceNameValuejLabel;
    // End of variables declaration//GEN-END:variables

public void setEvent(){
    MenuHandler handler = new MenuHandler();
    WindowEventHandler windowHandler = new WindowEventHandler();
    jMenuItemNewTrace.setActionCommand("New Trace");
    jMenuItemNewTrace.addActionListener(handler);
    jMenuItemStopTrace.setActionCommand("Stop Trace");
    jMenuItemStopTrace.addActionListener(handler);
    jMenuItemCommandEditor.setActionCommand("commandEditor");
    jMenuItemCommandEditor.addActionListener(handler);
    jMenuItemOption.setActionCommand("option");
    jMenuItemOption.addActionListener(handler);
    jMenuItemAbout.setActionCommand("about");
    jMenuItemAbout.addActionListener(handler);
    this.addWindowListener(windowHandler);
    jMenuItemMflags.setActionCommand("openMflags");
    jMenuItemMflags.addActionListener(handler);
    jMenuItemOpenCardOpener.setActionCommand("openCardFilePanel");
    jMenuItemOpenCardOpener.addActionListener(handler);
    jMenuItemDro.setActionCommand("openDro");
    jMenuItemDro.addActionListener(handler);
    jMenuItemOpenRunLogs.setActionCommand("openRunLogs");
    jMenuItemOpenRunLogs.addActionListener(handler);
    jMenuItemExtractEditor.setActionCommand("mapRow");
    jMenuItemExtractEditor.addActionListener(handler);
    jMenuItemExtractPath.setActionCommand("openExtractPath");
    jMenuItemExtractPath.addActionListener(handler);
//    jMenuItemIn0800Card.setActionCommand("openCardFile");
//    jMenuItemBr0501card.setActionCommand("openCardFile");
//    jMenuItemAM10000.setActionCommand("openCardFile");
//    jMenuItemAM2000.setActionCommand("openCardFile");
//    jMenuItemAM3000.setActionCommand("openCardFile");
//    jMenuItemIF0001.setActionCommand("openCardFile");
//    jMenuItemIF0002.setActionCommand("openCardFile");
//    jMenuItemIF0003.setActionCommand("openCardFile");
//    jMenuItemIF0004.setActionCommand("openCardFile");
//    jMenuItemIF0005.setActionCommand("openCardFile");
    
    
    
//    jMenuItemIn0800Card.addActionListener(handler);
//    jMenuItemBr0501card.addActionListener(handler);
//    jMenuItemAM10000.addActionListener(handler);
//    jMenuItemAM2000.addActionListener(handler);
//    jMenuItemAM3000.addActionListener(handler);
//    jMenuItemIF0001.addActionListener(handler);
//    jMenuItemIF0002.addActionListener(handler);
//    jMenuItemIF0003.addActionListener(handler);
//    jMenuItemIF0004.addActionListener(handler);
//    jMenuItemIF0005.addActionListener(handler);
    
//    jMenuItemNewTrace.addMenuKeyListener(l);
}
public void setProperty(){
    setIconImage(new AppIcon().getAppIcon());
   jMenuItemStopTrace.setVisible(false);
//   traceNameLabel.setVisible(false);
   jProgressBar.setVisible(false);
   jLabelProgress.setVisible(false);
//   jScrollPane1.setVisible(false);
//   String log4jPath = Path.LOG4J_PATH;
//   System.setProperty("log4j.configurationFile", log4jPath);
   
   guiModal.setProgramBarLabel(jLabelProgress);
   guiModal.setShowOutput(jLabelShowOutput);
   guiModal.setProgresBar(jProgressBar);
   guiModal.setTraceNameLabel(traceNameLabel);
   guiModal.setTraceNameValue(tranceNameValuejLabel);
   guiModal.setStopTraceMenuItem(jMenuItemStopTrace);
   guiModal.setOutputLogsPane(jTextPaneOutputLogs);
   guiModal.setOutputScrollPane(jScrollPane1);
   
}



}
